### ISSUE TITLE
Implementing Null-Safety

### ISSUE THREAD

**Issue by TitanKing** [kuzzleio/sdk-dart#70]
## Expected Behavior
Ability to use kuzzle flutter package as a null-safety package.

## Current Behavior
Impossible to use with sound null-safety.

## Possible Solution
Create a null-safe package as with [instructions here](https://flutter.dev/docs/null-safety).

## Steps to Reproduce
After following [these steps](https://dart.dev/null-safety/migration-guide) and having included all null-safety packages, kuzzle flutter will fail.

## Context (Environment)
Since Flutter is almost ready to transfer to stable with full null-safety capabilities, it will be great for the kuzzle project to get receive the expose it deserves by being null-safe ready. I attest to this projects quality but it completely lacks the attention it deserves. It is really a great alternative to many paid projects. It being null-safe people will trust its maintainability. Also, I want to use it in a null-safe project and this is the last package incompatible. If I have time I will start converting and doing pull requests.

**Comment by jenow** [comment]
https://github.com/kuzzleio/sdk-dart/releases/tag/3.0.0
