### ISSUE TITLE
example folder is not found

### ISSUE THREAD

**Issue by pierre-gancel** [kuzzleio/sdk-dart#90]
<img width="714" alt="Screenshot 2021-06-15 at 17 19 40" src="https://user-images.githubusercontent.com/69810198/122079617-dfcb6180-cdfd-11eb-9773-137463ecf319.png">

**Comment by Aschen** [comment]
Hi @pierre-gancel 

There is a 404 because this folder does not exists in this repository.

You can find examples in the documentation: https://docs.kuzzle.io/sdk/dart/2/

**Comment by Aschen** [comment]
I just understood that it comes from the README :facepalm: 

I changed it, thanks :+1:
